title: Yichen's Homepage
page-top-title: Yichen Ding（丁熠晨）
top-section-bg-text: Be what you wanna be
home-subtitle: Yichen&ensp;|&ensp;丁熠晨
copyright-text: '&copy; Yichen Ding 2025-2026. All Rights Reserved.'
